---
ID: "5f34b3ce-cf30-48f8-9064-da31392f8f38"
Parent: "7bc635a0-f17d-4101-81d4-621d4c37dcd0"
Template: "7bc635a0-f17d-4101-81d4-621d4c37dcd0"
Path: /sitecore/templates/Data Exchange/Providers/Xml/Data Access/Value Readers/Xml Node Value Reader/__Standard Values
DB: master
SharedFields:
- ID: "3c7f78cc-0c5c-4076-80ef-9a49fda5ff96"
  Hint: ConverterType
  Value: Sitecore.DataExchange.Custom.XmlProvider.DataAccess.Readers.XmlNodeValueReaderConverter, Sitecore.DataExchange.Custom.XmlProvider
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170127T141439Z
