---
ID: "71cddbe6-d325-4cbd-9348-359d798e2c7d"
Parent: "f4160db7-2bac-41e9-b8b4-772d3ecb575d"
Template: "7413953f-763f-44de-ac9b-2a29c6b5a0c5"
Path: /sitecore/templates/Branches/Data Exchange/Providers/Xml/Commands/Xml Value Readers/New Item Settings
DB: master
BranchID: "d1dcfbcc-dacc-414f-bdc4-8a3e1c41988b"
SharedFields:
- ID: "8e3ba4db-4577-4a5c-a54a-7a1775596e19"
  Hint: NewItemTemplate
  Value: "{D0526941-615E-464A-9F7D-12907AB66F05}"
- ID: "a46a30eb-0a43-4742-8f5d-a6ab94a7ad58"
  Hint: NewItemName
  Value: Xml
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{81FE94AC-5AED-45DC-B326-C2CA8C9DBADD}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180626T071700Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
